server:
  port: ${SERVER_PORT:9090}

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 9000000         # 15 phút (Access Token)
  google:
    client-id: ${GOOGLE_CLIENT_ID}

vnp:
  pay_url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return_url: ${VNP_RETURN_URL:http://localhost:5173/payment-return}
  tmn_code: ${VNP_TMN_CODE:LK1L9TK0}
  hash_secret: ${VNP_HASH_SECRET:2W8S35CGC4KBYYG26V2YC8OBII85TTLU}
  api_url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
spring.task.scheduling.pool.size: 2    # Cho phép @Scheduled chạy

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:"dskwek4ju"}
  api-key: ${CLOUDINARY_API_KEY:"575491814491519"}
  api-secret: ${CLOUDINARY_API_SECRET:"t-az2VOpw3jOm1hdcD2SEF0C2gw"}
